name: Image Size Check

on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - '**/*.png'
      - '**/*.jpg'
      - '**/*.jpeg'
      - '**/*.gif'
      - '**/*.webp'

jobs:
  check-image-sizes:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install image-size

      - name: Fetch base branch
        run: |
          git remote add upstream https://github.com/${{ github.repository }}.git
          git fetch upstream ${{ github.base_ref }}
          
          echo "Debug information:"
          echo "PR head ref: ${{ github.head_ref }}"
          echo "PR base ref: ${{ github.base_ref }}"
          echo "PR repo: ${{ github.event.pull_request.head.repo.full_name }}"
          echo "Base repo: ${{ github.repository }}"
          
          echo "\nGit remotes:"
          git remote -v
          
          echo "\nChanged files:"
          git diff --name-only upstream/${{ github.base_ref }} HEAD

      - name: Check image sizes
        run: |
          cat << 'EOF' > check-images.js
          const imageSize = require('image-size');
          const fs = require('fs');
          const path = require('path');
          const { execSync } = require('child_process');

          const MAX_SIZES = {
            '.jpg': 200 * 1024,  // 200KB
            '.jpeg': 200 * 1024, // 200KB
            '.png': 150 * 1024,  // 150KB
            '.gif': 300 * 1024,  // 300KB
            '.webp': 100 * 1024  // 100KB
          };

          // Maximum dimensions
          const MAX_DIMENSIONS = {
            width: 1920,
            height: 1080
          };

          let hasError = false;

          function checkImage(filePath) {
            const stats = fs.statSync(filePath);
            const fileSize = stats.size;
            const ext = path.extname(filePath).toLowerCase();
            const maxSize = MAX_SIZES[ext];

            if (!maxSize) return;

            console.log(`\nChecking: ${filePath}`);

            // Check file size
            if (fileSize > maxSize) {
              console.error(`❌ Size Error: File is ${(fileSize/1024).toFixed(2)}KB. Maximum allowed is ${(maxSize/1024).toFixed(2)}KB`);
              hasError = true;
            } else {
              console.log(`✅ Size OK: ${(fileSize/1024).toFixed(2)}KB`);
            }

            // Check dimensions
            const dimensions = imageSize(filePath);
            console.log(`📏 Dimensions: ${dimensions.width}x${dimensions.height}`);

            if (dimensions.width > MAX_DIMENSIONS.width || dimensions.height > MAX_DIMENSIONS.height) {
              console.error(`❌ Dimension Error: Maximum allowed dimensions are ${MAX_DIMENSIONS.width}x${MAX_DIMENSIONS.height}`);
              hasError = true;
            }

            // Suggestions for optimization
            if (ext === '.jpg' || ext === '.jpeg') {
              console.log('💡 Tip: Consider using WebP format for better compression');
            }
            if (fileSize > maxSize) {
              console.log('💡 Tip: Try using tools like squoosh.app or tinypng.com for optimization');
            }
          }

          try {
            // Get files changed in PR by comparing with base branch
            const command = `git diff --name-only upstream/${process.env.BASE_REF} HEAD`;
            console.log('Running command:', command);
            
            const changedFiles = execSync(command)
              .toString()
              .split('\n')
              .filter(file => file && file.match(/\.(jpg|jpeg|png|gif|webp)$/i));

            console.log('\nChanged files detected:', changedFiles);

            if (changedFiles.length === 0) {
              console.log('No image files were changed in this PR.');
              process.exit(0);
            }

            console.log('🔍 Checking image sizes and dimensions...\n');
            changedFiles.forEach(file => {
              if (fs.existsSync(file)) {
                checkImage(file);
              }
            });

            if (hasError) {
              console.error('\n❌ Image check failed! Please optimize the flagged images.');
              process.exit(1);
            } else {
              console.log('\n✅ All images passed the size and dimension checks!');
            }
          } catch (error) {
            console.error('Error:', error.message);
            console.error('Stack:', error.stack);
            process.exit(1);
          }
          EOF

          node check-images.js
        env:
          BASE_REF: ${{ github.base_ref }}
          HEAD_SHA: ${{ github.event.pull_request.head.sha }}

permissions:
  contents: read
  pull-requests: read 