name: Auto Merge PR on Comment

on:
  issue_comment:
    types: [created]

jobs:
  automerge:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == '@auto_merge'
    runs-on: ubuntu-latest
    steps:
      - name: Check required status checks and mergeability
        id: checks
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            const pr = await github.pulls.get({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
            });
            let reason = '';
            if (pr.data.mergeable_state !== 'clean') {
              if (pr.data.mergeable_state === 'dirty') {
                reason = 'This PR has merge conflicts.';
              } else if (pr.data.mergeable_state === 'blocked') {
                reason = 'This PR is blocked by required status checks or other branch protection rules.';
              } else if (pr.data.mergeable_state === 'unknown') {
                reason = 'The mergeability of this PR could not be determined. Please try again later.';
              } else {
                reason = `This PR cannot be auto-merged. mergeable_state: ${pr.data.mergeable_state}`;
              }
              core.setOutput('can_merge', 'false');
              core.setOutput('reason', reason);
            } else {
              core.setOutput('can_merge', 'true');
            }
      - name: Comment if cannot merge
        if: steps.checks.outputs.can_merge == 'false'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: `:x: Auto-merge not possible: ${{ steps.checks.outputs.reason }}`
            })
      - name: Auto-merge PR
        if: steps.checks.outputs.can_merge == 'true'
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            await github.pulls.merge({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.issue.number,
              merge_method: 'squash'
            })