name: PR Auto-Merge Eligibility Check

on:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
  contents: read
  pull-requests: write

jobs:
  check-allowlist:
    uses: ./.github/workflows/pr-allowlist-check.yml
    with:
      pr_number: ${{ github.event.pull_request.number }}

  comment:
    needs: check-allowlist
    runs-on: ubuntu-latest
    if: needs.check-allowlist.outputs.allowed == 'true'
    steps:
      - name: Comment on PR if auto-merge is allowed
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.PAT_TOKEN }}
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "✔️ Auto merging is allowed in this PR and you can do this by commenting @auto_merge"
            }) 
